### ISSUE TITLE
Make test artifacts URL in Action summary clickable 

### ISSUE THREAD

**Issue by zmiklank** [sclorg/testing-farm-as-github-action#135]
This will need slight adjustment in the markdown generated for GitHub Action summary.

This is a good first issue. Contributions are welcome. Feel free to ask more questions, if needed.

**Comment by jamacku** [comment]
Current state:
![Screenshot from 2024-03-12 13-00-09](https://github.com/sclorg/testing-farm-as-github-action/assets/2879818/2b7f8a92-a1e2-4409-984d-b1f31a1009af)
