### ISSUE TITLE
Missing a few inputs

### ISSUE THREAD

**Issue by fernflower** [sclorg/testing-farm-as-github-action#16]
The leapp team has big plans with this action, thanks a lot for working on it!
Looking at the api we are missing a few inputs though. I will be attaching links to our home-made composite action's inputs for better visibility.

The missing inputs:
* Everything related to artifacts installation. We install only from public copr, so in our case it's `copr` name - https://github.com/oamg/testing-farm-service-action/blob/cc3f1e3bf5e0ff2b97bfe96552107acee475875c/action.yml#L27 and a comma-separated list of `artifacts` to be installed.
* Passing of tmt-context (as defined in environments.tmt.context in the tft api). This is necessary to filter out tests based on certain distro.
https://github.com/oamg/testing-farm-service-action/blob/cc3f1e3bf5e0ff2b97bfe96552107acee475875c/action.yml#L36
* `arch` https://github.com/oamg/testing-farm-service-action/blob/main/action.yml#L24 .

**Comment by phracek** [comment]
All issues were addressed. Closing this issue.
