### ISSUE TITLE
RFE: Support multi-host testing

### ISSUE THREAD

**Issue by engelmi** [sclorg/testing-farm-as-github-action#164]
Testing Farm supports [tmt's multihost testing](https://tmt.readthedocs.io/en/stable/guide.html#multihost-testing). According to the [TF multihost](https://docs.testing-farm.io/Testing%20Farm/0.1/test-request.html#multihost-testing) documentation, it is disabled by default and for enabling the pipeline type setting must be set:
```json
{
    "settings": {
        "pipeline": {
            "type": "tmt-multihost"
        }
    }
}
```
Or using the testing farm CLI with `--pipeline-type tmt-multihost`. 

As far as I've seen, it is not yet possible to pass this flag to the GitHub Action - so it would be great to add it. If this RFE is accepted, I can also start working on it and provide a PR for it.

__Background:__
In [Eclipse BlueChi](https://github.com/eclipse-bluechi/bluechi/) we are using the multihost testing and would like to use this GH Action. But since it doesn't support enabling multihost testing yet, we have to use the testing farm cli directly.

**Comment by zmiklank** [comment]
Hi, thanks for creating the issue and for your willingness to contribute :).

I see the multihost testing has a few [limitations](https://docs.testing-farm.io/Testing%20Farm/0.1/test-request.html#_current_limitations) and I haven't really heard about this TF feature myself. @thrix, could you please share your opinion, if it would make sense to add such feature to TFAGA?

**Comment by thrix** [comment]
@zmiklank hi, it would be great to support setting the pipeline type in TFAGA. For now this is a previous of our new pipeline that will support multihost, in the future it will be the default one. We might be introducing this way other pipeline types, so I think supporting that field in general might be useful.

**Comment by zmiklank** [comment]
> @zmiklank hi, it would be great to support setting the pipeline type in TFAGA. For now this is a previous of our new pipeline that will support multihost, in the future it will be the default one. We might be introducing this way other pipeline types, so I think supporting that field in general might be useful.

@thrix Thank you for the answer!

@engelmi Please feel free to start working on this if you want.

**Comment by engelmi** [comment]
Sure thing :) 

I already had a quick look and found that the zod schema for the `testing-farm` package needs to be updated. I created the PR for it (https://github.com/redhat-plumbers-in-action/testing-farm/pull/112) and wait for it to be merged. After the new version is released, I continue here.

**Comment by jamacku** [comment]
[testing-farm@v1.9.0](https://www.npmjs.com/package/testing-farm/v/1.9.0) was just released. It contains:

- https://github.com/redhat-plumbers-in-action/testing-farm/pull/112

**Comment by engelmi** [comment]
Thanks! @jamacku 
Just opened a PR based on it.
