### ISSUE TITLE
CI job finished but didn't update the job status in pull request

### ISSUE THREAD

**Issue by yih-redhat** [sclorg/testing-farm-as-github-action#165]
### Version

sclorg/testing-farm-as-github-action@v1

### OS version of the container image

RHEL 9

### Description

I am using github plugin sclorg/testing-farm-as-github-action@v1 to run CI test. If I trigger one or two jobs in my pull request, it can finish and update the result in pull request.

And then I triggered 15 jobs at the same time in https://github.com/yih-redhat/tmt-demo/pull/35 , now it's been 18 hours and all job status is still 'Pending — Build started' .   I clicked the 'detail' of these jobs, and found that they are already finished and about 12 of /15 jobs  passed.  
I also clicked 'Actions' and then found CI job, clicked into it, it shows all jobs are failed, which is not correct because actually some jobs passed. Click on one failed job, the error message is:
"parse error: Invalid numeric literal at line 1, column 7
Error: Process completed with exit code 4."

### Reproducer

Reproduce steps:
1. You can find all the information and logs at https://github.com/yih-redhat/tmt-demo/pull/35,  I will keep it there while you are looking into this issue. And you can also follow these steps to reproduce it.
2. Go to https://github.com/yih-redhat/tmt-demo (a demo project to verify before we migrate to testing-farm)
3.  Submit a pull request , add comment "/test-rhel-9-4"
4.  Wait a while, github workflow will trigger all our test cases. (should be 15 jobs)

**Comment by yih-redhat** [comment]
@phracek also need to take a look of this one.

**Comment by zmiklank** [comment]
Hello @yih-redhat, version 1 of tfaga is no longer supported. Feel free to migrate to v2.
