### ISSUE TITLE
CI job passed and test script exit 0, but failed by timeout

### ISSUE THREAD

**Issue by yih-redhat** [sclorg/testing-farm-as-github-action#166]
### Description

Please check log at http://artifacts.osci.redhat.com/testing-farm/7df7ef54-3fa5-46fd-8801-b1ce2e37f94b/

I can see  the job is already finished and exit with 0, but however it still wait for that process to finish and finally timeout.

+ sudo podman system reset --force
 A "/etc/containers/storage.conf" config file exists.
Remove this file if you did not modify the configuration.
+ sudo rm -rf /tmp/tmp.tbHrQIG4kt
+ exit 0

Maximum test time '150m' exceeded.
Adjust the test 'duration' attribute if necessary.
https://tmt.readthedocs.io/en/stable/spec/tests.html#duration

A new job that can print out leftover or orphaned process has been created and is running now. https://github.com/yih-redhat/tmt-demo/pull/36

**Comment by yih-redhat** [comment]
Changed from v1 to main at https://github.com/yih-redhat/tmt-demo/blob/main/.github/workflows/rhel-9-4.yaml#L452

Now this test is run with main branch now https://github.com/yih-redhat/tmt-demo/pull/37

**Comment by yih-redhat** [comment]
@phracek Hi, do you have time to take a look of this issue this week?

**Comment by zmiklank** [comment]
Hello @yih-redhat, is this issue related to tfaga v2?

**Comment by yih-redhat** [comment]
What do you mean "tfaga v2"?
I changed to sclorg/testing-farm-as-github-action@v2, and still have the same issue.

**Comment by zmiklank** [comment]
I meant version 2 of testing farm as github action. So then yes.
Thanks for creating the issue, we will look into it. Also contributions are welcome.

**Comment by zmiklank** [comment]
@yih-redhat 
I see, that [the action is failing as it should be](https://github.com/yih-redhat/tmt-demo/actions/runs/8751998014):
![image](https://github.com/sclorg/testing-farm-as-github-action/assets/90186537/1af29930-7c41-4efd-be76-7b2dea4c208a)


Isn't the reason of this behavior [in you setup](https://github.com/yih-redhat/tmt-demo/blob/760f5114c5bfb6ff88abff4ea5cb370af45dfe38/.github/workflows/rhel-9-4.yaml#L441)?

**Comment by jamacku** [comment]
Also:

```
Maximum test time '150m' exceeded.
Adjust the test 'duration' attribute if necessary.
```
