### ISSUE TITLE
requested URL not found

### ISSUE THREAD

**Issue by yih-redhat** [sclorg/testing-farm-as-github-action#198]
### Type of issue

None

### Description

Our CI is using tfaga, but I cannot find the log for one failed case.

1. Go to https://github.com/virt-s1/rhel-edge/pull/7931 , and click 'Details' of 'Testing Farm - edge-rhel-8.10-x86'
2. Now we are at page https://artifacts.osci.redhat.com/testing-farm/57c01e4c-06cf-4d9b-a178-3339d8e2edf8/
3. Click on failed case and click testout.log
4. I got 'The requested URL /testing-farm/57c01e4c-06cf-4d9b-a178-3339d8e2edf8/work-edge-x86-installervecdlt5d/tmt/plans/edge-test/edge-x86-installer/execute/data/guest/default-0/tmt/tests/edge-test-1/output.txt was not found on this server.'

**Comment by zmiklank** [comment]
Hi, this issue seems to be related to the Testing Farm itself, not to the tfaga.
