### ISSUE TITLE
Unable to resolve action `sclorg/testing-farm-as-github-action@v1`

### ISSUE THREAD

**Issue by jamacku** [sclorg/testing-farm-as-github-action#22]
Currently documentation shows an example of using `testing-farm-as-github-action` as `sclorg/testing-farm-as-github-action@v1`. But since there is no tag `v1` this will resolve with following error:

```
Error: Unable to resolve action `sclorg/testing-farm-as-github-action@v1`, unable to find version `v1`
```

As noted in https://github.com/sclorg/testing-farm-as-github-action/pull/19#issue-1123969843 you need to add tag `v<major-version>` in order to use it like that. If not, users need to reference the exact minor version, at the moment it's `v1.1` and then setup dependabot to automatically look for updates.

---

From Docs:

We recommend creating releases using semantically versioned tags – for example, v1.1.3 – and keeping major (v1) and minor (v1.1) tags current to the latest appropriate commit. For more information, see "[About custom actions](https://docs.github.com/en/actions/creating-actions/about-custom-actions#using-release-management-for-actions)" and "[About semantic versioning](https://docs.npmjs.com/about-semantic-versioning)".

**Comment by phracek** [comment]
Thanks for this issue.

I have to create an automation, how to do it as soon as PR is merged.

**Comment by phracek** [comment]
The tag `v1` is still moving manually, but trying to find out an action for it.

**Comment by jamacku** [comment]
@phracek You can try something like this: https://github.com/redhat-plumbers-in-action/differential-shellcheck/blob/main/.github/workflows/publish-release.yml

Just exclude release-drafter action. Then when you publish new minor tag, major tag will get automatically updated.

**Comment by phracek** [comment]
See how publish-release.yml works. Issue https://github.com/release-drafter/release-drafter/issues/1073
