### ISSUE TITLE
Provide ability to specify plan-filter

### ISSUE THREAD

**Issue by spetrosi** [sclorg/testing-farm-as-github-action#222]
### Type of issue

Feature Request

### Description

Testing farm and tmt supports specifying [plan-filter](https://docs.testing-farm.io/Testing%20Farm/0.1/test-request.html#plan-filter).
The role supports only `tmt_plan_regex`, which is different per description.
I need support for `plan-filter` to filter plans by tags.

| Input Name | Description | Default value |
|------------|-------------|---------------|
| `tmt_plan_filter` | A filter used to select tmt plans | '' |

Possible values: `"tag:mytest"`

**Comment by phracek** [comment]
@spetrosi Thanks for this issue. I will take care of it.

This means, user can select either plan in "plans" directory or "tag:mytest" that is present in the plan directory.
Both of them can be present?

**Comment by spetrosi** [comment]
> @spetrosi Thanks for this issue. I will take care of it.
> 
> This means, user can select either plan in "plans" directory or "tag:mytest" that is present in the plan directory. Both of them can be present?

I am not sure I understoow what you said. Are asking if action must allow for `tmt_plan_regex` and `tmt_plan_filter`  to be used together?
I guess if API allow for this, yes.
I.e. in a scenario where I store plans in subdirectories of `/plans` dir, and those plans have the same tags, I might want to select plans tagged with desired tags from a single directory only.
