### ISSUE TITLE
Use the newly supported authorization header when authenticating with Testing Farm

### ISSUE THREAD

**Issue by jamacku** [sclorg/testing-farm-as-github-action#224]
### Type of issue

Feature Request

### Description

TF now supports authentication using a bearer token, and we should use it!

Also, `api_key` is now marked as deprecated:
https://api.dev.testing-farm.io/redoc#operation/request_a_new_test_v0_1_requests_post

/cc @thrix - FYI

**Comment by thrix** [comment]
the team says it should be safe to migrate, so +1 from us @jamacku 

And thanks for following us

**Comment by jamacku** [comment]
@thrix Thanks for feedback.
