### ISSUE TITLE
tmt_plan_filter is being ignored

### ISSUE THREAD

**Issue by WOnder93** [sclorg/testing-farm-as-github-action#230]
### Type of issue

Bug Report

### Description

Example: https://github.com/WOnder93/selinux-testsuite/actions/runs/10721083736/job/29728763570

I'm passing `tmt_plan_filter: tag:ci`, yet both plans are executed instead of only the matching one and in the pipeline logs there is only `"plan_filter":null` with no sign of the filter being passed to the actual TF request.

**Comment by jamacku** [comment]
I'm pretty sure that you are missing `'` in your workflow. Could you please try `tmt_plan_filter: 'tag:ci'`?

**Comment by WOnder93** [comment]
Nope, that didn't help: https://github.com/WOnder93/selinux-testsuite/actions/runs/10722112585/job/29732267688

**Comment by jamacku** [comment]
Thanks for trying. I'll have a look.

**Comment by jamacku** [comment]
@WOnder93 I have submitted PR with the fix. You can try it by using `jamacku/testing-farm-as-github-action@filter` instead of `sclorg/testing-farm-as-github-action@v3.1.1`.

**Comment by WOnder93** [comment]
I tested with current `sclorg/testing-farm-as-github-action@main`, and it works, thanks!

**Comment by jamacku** [comment]
@WOnder93 Thank you for testing :+1:
