### ISSUE TITLE
support image mode runner of testing-farm

### ISSUE THREAD

**Issue by yih-redhat** [sclorg/testing-farm-as-github-action#243]
### Type of issue

Feature Request

### Description

testing-farm team plan to support Fedora, CentOS Stream and RHEL runners in Image Mode, it will come soon, but till this moment it's not ready yet.

https://gitlab.com/testing-farm/general/-/blob/rfd5-testing-image-mode/rfd/rfd5-testing-image-mode.adoc?ref_type=heads#user-content-composes

File this issue to ask if tfaga has plan to support image mode runners.

**Comment by jamacku** [comment]
We plan to add support once it is publicly available in Testing Farm.

**Comment by phracek** [comment]
@thrix Please let as know when image mode will be available in testing-farm. The reference to API would be welcome.

**Comment by yih-redhat** [comment]
Hi @jamacku @phracek , I am one of the early adopters of image mode testing, and from the mail I got they said the image mode is ready in testing-farm and tmt now, but I still need tfaga to run my CI.
May I know when I can expect this feature in tfaga? that will be very helpful, thanks.

**Comment by jamacku** [comment]
@yih-redhat [From what I see](https://gitlab.com/testing-farm/general/-/blob/rfd5-testing-image-mode/rfd/rfd5-testing-image-mode.adoc?ref_type=heads), there is only an initial MVP. Support should be available in the next release, and then we can add support.

**Comment by jamacku** [comment]
Testing Farm announced image mode, which is now officially available for RHEL-9.6.0, Fedora-40, and CentOS-Stream 9.

From what I saw, Testing Farm GHA should support it out of the box. There are no changes needed from our side. Just pick image mode [compose and architecture](https://gitlab.com/testing-farm/general/-/blob/e1a7ed1027e0a5c1871300c210770e20b3858050/rfd/rfd5-testing-image-mode.adoc#user-content-composes).

If you find any issues, please let us know.
