### ISSUE TITLE
Got error in PR workflow but works well in push

### ISSUE THREAD

**Issue by smyle10** [sclorg/testing-farm-as-github-action#255]
### Type of issue

Bug Report

### Description

Hi, I created a simple workflow to try tfaga and got this error when triggering by PR https://github.com/smyle10/tmt-demo/actions/runs/12157294307/job/33902766420 (while the test job in testing farm passed successfully)

meanwhile, the job triggering by pushing to main branch works all good: https://github.com/smyle10/tmt-demo/actions/runs/12156709370

**Comment by jamacku** [comment]
Hi, the error message suggests that you are missing permissions `Resource not accessible by integration.` You can't run action `on:  pull_request`. You must use `on pull_request_target` if you wish to trigger an action when a new PR is opened.

Example: https://github.com/sclorg/testing-farm-as-github-action/blob/main/.github/workflows/base-test-pr-trigger.yml
