### ISSUE TITLE
Bug: do not add artifacts if they are not specified in inputs.

### ISSUE THREAD

**Issue by phracek** [sclorg/testing-farm-as-github-action#30]
It looks like artifacts are not handled properly:

```bash
     "secrets": {"QUAY_USERNAME": "***", "QUAY_TOKEN": "***"},
      "artifacts": [{"type": "fedora-copr-build", "id": ":epel-7-x86_64"}],
      "tmt": {
        "context": {}

```

See job:
https://github.com/sclorg/nginx-container/runs/5213155317?check_suite_focus=true

sclorg organization does not need artifacts.

**Comment by phracek** [comment]
@fernflower Can you please have a look at it?
The question from my side is, how do you test GitHub Action?

**Comment by fernflower** [comment]
I test this in github action that leapp uses to trigger tests. There is one limitation - you can't test it in a PR opened against leapp's github action (as changes to the action won't be applied until it's merged), so I force push the changes to the master branch of my leapp fork (like this for example https://github.com/fernflower/leapp/commit/b5203ccad820362f19c506faf3be4faff1f6b74b), then say '/rerun' (our action is triggered by this comment https://github.com/fernflower/leapp/actions/runs/1840154797/workflow#L14) and get the desired action actually run like https://github.com/fernflower/leapp/actions/runs/1840154797
