### ISSUE TITLE
set-output is deprecated

### ISSUE THREAD

**Issue by zmiklank** [sclorg/testing-farm-as-github-action#55]
Source: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

Instead the GITHUB_STATE and GITHUB_OUTPUT environment files should be used.

**Comment by phracek** [comment]
What about to use `env` like it is described here: https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-environment-variable

**Comment by zmiklank** [comment]
GitHub on their blog wrote following:
"A workflow using save-state or set-output should be updated to write to the new GITHUB_STATE and GITHUB_OUTPUT environment files".

But I am not sure.
