### ISSUE TITLE
Switch default value of `update_pull_request_status` to false.

### ISSUE THREAD

**Issue by zmiklank** [sclorg/testing-farm-as-github-action#65]
We should not count with a fact that user wants to use the TFaGA in a pull request trigger.
So the `update_pull_request_status`'s default value should be set to `false`.

This change will require new release, as it is not backward compatible.

**Comment by phracek** [comment]
@phracek has to look, how this change affects the https://github.com/sclorg GitHub Actions.

**Comment by zmiklank** [comment]
This seems to have a go.

I am assigning myself to this.

**Comment by zmiklank** [comment]
After a team discussion this issue has a go.

It should be released in v2.0.0 and the api incompatibility mentioned in release changelog.
I will also revise, if any other api-related change would need to be done, so that we could ship it in the v.2.0.0 if applicable.
