### ISSUE TITLE
Discuss, if TFaGA should end with error if tests fail.

### ISSUE THREAD

**Issue by zmiklank** [sclorg/testing-farm-as-github-action#67]
Currently, if the tests fail, the action can set PR status to failed, but the action itself ends with success. It ends with failure only when some infra error occurs, or when there is some error in the action.

However I would say this is kind of misleading, because the action can be use also with other triggers, and if user wants to trigger it for example with push trigger it could lead to situation when the tests would seem to be passing, but would be failing in reality.

**Comment by phracek** [comment]
> However I would say this is kind of misleading, because the action can be use also with other triggers, and if user wants to trigger it for example with push trigger it could lead to situation when the tests would seem to be passing, but would be failing in reality.

I don't follow how the tests would be passing and in reality not. This is a problem with test suite and not TFaGA. The actual state seems to be fine as you wrote at the beginning.

**Comment by zmiklank** [comment]
> I don't follow how the tests would be passing and in reality not. This is a problem with test suite and not TFaGA. The actual state seems to be fine as you wrote at the beginning.

Example:
All of these tests seem to be passing:
https://github.com/sclorg/s2i-php-container/actions/runs/3575598789
But some of them actually failed, e.g., this one [1].

[1] https://github.com/sclorg/s2i-php-container/actions/runs/3575598789/jobs/6012345562

**Comment by frenzymadness** [comment]
I think we can discuss this tomorrow at the meeting.

**Comment by zmiklank** [comment]
That is the plan :).

**Comment by zmiklank** [comment]
This seems to have a go.

I am assigning myself to this.

**Comment by zmiklank** [comment]
Implemented, closing.
